score_module_a_test_stage_6:
  # PROXY: A - Serveris töötab veebiserver
  - name: Proxy serveris töötab veebiserver
    id: 30
    points: 0.5
    hostname: a_proxy
    get_content:
      cmd1: |
        netstat -tl
    assert:
      - "'http' in result1.stdout"
  # PROXY: A - Server on pöördproksina WEB serverile
  - name: Proxy server on pöördproksina WEB serverile
    id: 31
    points: 1
    hostname: a_web
    cmd2_hostname: a_proxy
    get_content:
      cmd1: |
        echo "Hello from Arbitaja" > /var/www/security/test.txt
      cmd2: |
        curl 192.168.20.10/test.txt
    assert:
      - "'Hello from Arbitaja' in result2.stdout"
  # PROXY: A - Kuvatakse infoturbe uudiskirja sisu
  - name: Proxy kuvatakse infoturbe uudiskirja sisu
    id: 32
    points: 0.5
    hostname: a_proxy
    get_content:
      cmd1: |
        curl localhost/infokiri.txt
    assert:
      - "'Infokirja' in result1.stdout"
  # PROXY: A - Pöördproksi päises on eestiasi-proxy viide
  - name: Pöördproksi päises on eestiasi-proxy viide
    id: 33
    points: 1
    hostname: a_proxy
    get_content:
      cmd1: |
        curl localhost/infokiri.txt -v
    assert:
      - "'x-secured-by: eestiasi-proxy' in result1.stderr"
  # FW: A - Veebiliiklus on suunatud PROXY serverile
  - name: FW veebiliiklus on suunatud PROXY serverile
    id: 34
    points: 1
    hostname: a_fw
    cmd2_hostname: a_admin
    get_content:
      cmd1: |
        netstat -tl
      cmd2: |
        OUTSIDE_IP=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 \
          -o PreferredAuthentications=publickey -i /home/meister/.ssh/modulea meister@192.168.10.1 \
          "ip addr | grep ens18 | grep -oE \"172\.25\.[0-9]{1,3}\.[0-9]{1,3}\" | head -1")
        curl $OUTSIDE_IP/infokiri.txt
    assert:
      - "'http' not in result1.stdout"
      - "'Infokirja' in result2.stdout"
